use_frameworks!

platform :ios, '12.0'

target 'CalendarRangeView_Example' do
  pod 'CalendarRangeView', :path => '../'
  pod 'SnapKit'

  target 'CalendarRangeView_Tests' do
    inherit! :search_paths

    
  end
end
